#!/usr/bin/env python3
"""
Interactive Configuration Setup Helper
Helps users set up their environment configuration step by step
"""

import os
import sys
import getpass
from pathlib import Path

def print_header(title):
    """Print a formatted header"""
    print(f"\n{'='*60}")
    print(f"🔧 {title}")
    print(f"{'='*60}")

def print_step(step_num, title):
    """Print a formatted step"""
    print(f"\n📋 STEP {step_num}: {title}")
    print("-" * 50)

def get_user_input(prompt, default=None, required=True, password=False):
    """Get user input with validation"""
    while True:
        if password:
            value = getpass.getpass(f"{prompt}: ")
        else:
            if default:
                value = input(f"{prompt} [{default}]: ").strip() or default
            else:
                value = input(f"{prompt}: ").strip()
        
        if value or not required:
            return value
        
        if required:
            print("❌ This field is required. Please enter a value.")
        else:
            return ""

def load_existing_env():
    """Load existing .env file"""
    env_file = Path('.env')
    env_vars = {}
    
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    
    return env_vars

def save_env_file(env_vars):
    """Save environment variables to .env file"""
    env_content = """# Environment Variables for Web Monitor Bot
# Generated by setup_config.py

# Google Gemini API Key
# Get your key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY={gemini_api_key}

# AI Model Configuration
GEMINI_MODEL={gemini_model}

# Custom AI Analysis Prompt (optional)
{custom_prompt_line}

# Email Configuration (for notifications)
# Gmail SMTP Configuration
SMTP_SERVER={smtp_server}
SMTP_PORT={smtp_port}

# Gmail Account Settings
EMAIL_USERNAME={email_username}
EMAIL_PASSWORD={email_password}
EMAIL_TO={email_to}

# GitHub Configuration (for HTML Report Publishing)
{github_token_line}
{github_repo_line}
{reports_base_url_line}

# Report Management Configuration
MAX_REPORTS_TO_KEEP={max_reports_to_keep}
REPORTS_CLEANUP_DAYS={reports_cleanup_days}
ENABLE_REPORT_CLEANUP={enable_report_cleanup}
NOTIFICATION_TYPE={notification_type}

# Blog Monitoring Configuration (optional)
# BLOG_URL=https://cloud.google.com/blog/
# CHECK_INTERVAL_HOURS=6
""".format(
        gemini_api_key=env_vars.get('GEMINI_API_KEY', ''),
        gemini_model=env_vars.get('GEMINI_MODEL', 'gemini-2.5-flash'),
        custom_prompt_line=f'CUSTOM_AI_PROMPT="{env_vars["CUSTOM_AI_PROMPT"]}"' if env_vars.get('CUSTOM_AI_PROMPT') else '# CUSTOM_AI_PROMPT=""',
        smtp_server=env_vars.get('SMTP_SERVER', 'smtp.gmail.com'),
        smtp_port=env_vars.get('SMTP_PORT', '587'),
        email_username=env_vars.get('EMAIL_USERNAME', ''),
        email_password=env_vars.get('EMAIL_PASSWORD', ''),
        email_to=env_vars.get('EMAIL_TO', ''),
        github_token_line=f'GITHUB_TOKEN={env_vars["GITHUB_TOKEN"]}' if env_vars.get('GITHUB_TOKEN') else '# GITHUB_TOKEN=ghp_your_token_here',
        github_repo_line=f'GITHUB_REPO={env_vars["GITHUB_REPO"]}' if env_vars.get('GITHUB_REPO') else '# GITHUB_REPO=yourusername/your-repo-name',
        reports_base_url_line=f'REPORTS_BASE_URL={env_vars["REPORTS_BASE_URL"]}' if env_vars.get('REPORTS_BASE_URL') else '# REPORTS_BASE_URL=https://yourusername.github.io/your-repo-name',
        max_reports_to_keep=env_vars.get('MAX_REPORTS_TO_KEEP', '30'),
        reports_cleanup_days=env_vars.get('REPORTS_CLEANUP_DAYS', '30'),
        enable_report_cleanup=env_vars.get('ENABLE_REPORT_CLEANUP', 'true'),
        notification_type=env_vars.get('NOTIFICATION_TYPE', 'new_posts'),
    )
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"✅ Configuration saved to .env file")

def setup_ai_config(env_vars):
    """Setup AI configuration"""
    print_step(1, "AI Configuration (Required)")
    
    print("📋 You need a Google Gemini API key for AI analysis.")
    print("   1. Go to https://makersuite.google.com/app/apikey")
    print("   2. Create a new API key")
    print("   3. Copy the key below")
    
    current_key = env_vars.get('GEMINI_API_KEY', '')
    if current_key:
        print(f"   Current key: {current_key[:10]}...{current_key[-4:] if len(current_key) > 14 else current_key}")
    
    api_key = get_user_input("Gemini API Key", current_key)
    env_vars['GEMINI_API_KEY'] = api_key
    
    model = get_user_input("Gemini Model", env_vars.get('GEMINI_MODEL', 'gemini-2.5-flash'), required=False)
    env_vars['GEMINI_MODEL'] = model
    
    print("✅ AI configuration completed!")

def setup_email_config(env_vars):
    """Setup email configuration"""
    print_step(2, "Email Configuration (Required)")
    
    print("📧 Email notifications require Gmail app password setup:")
    print("   1. Enable 2-Factor Authentication on Gmail")
    print("   2. Go to https://myaccount.google.com/apppasswords")
    print("   3. Generate an 'App Password' for 'Mail'")
    print("   4. Use the 16-character password below")
    
    username = get_user_input("Gmail Username", env_vars.get('EMAIL_USERNAME', ''))
    env_vars['EMAIL_USERNAME'] = username
    
    current_password = env_vars.get('EMAIL_PASSWORD', '')
    if current_password:
        print(f"   Current password: {'*' * len(current_password)}")
    
    password = get_user_input("Gmail App Password", current_password, password=True)
    env_vars['EMAIL_PASSWORD'] = password
    
    recipient = get_user_input("Recipient Email", env_vars.get('EMAIL_TO', ''))
    env_vars['EMAIL_TO'] = recipient
    
    env_vars['SMTP_SERVER'] = 'smtp.gmail.com'
    env_vars['SMTP_PORT'] = '587'
    
    print("✅ Email configuration completed!")

def setup_github_config(env_vars):
    """Setup GitHub configuration"""
    print_step(3, "GitHub Configuration (Optional)")
    
    print("🌐 GitHub Pages hosting enables shareable report URLs.")
    print("   This is optional - you can still receive email reports without it.")
    
    setup_github = get_user_input("Set up GitHub Pages hosting? (y/n)", "n", required=False).lower()
    
    if setup_github in ['y', 'yes']:
        print("\n📋 GitHub setup instructions:")
        print("   1. Go to https://github.com/settings/tokens")
        print("   2. Create new token with 'repo' permissions")
        print("   3. Create/use a repository for hosting reports")
        print("   4. Enable GitHub Pages in repository settings")
        
        token = get_user_input("GitHub Token", env_vars.get('GITHUB_TOKEN', ''), required=False)
        if token:
            env_vars['GITHUB_TOKEN'] = token
        
        repo = get_user_input("GitHub Repository (username/repo)", env_vars.get('GITHUB_REPO', ''), required=False)
        if repo:
            env_vars['GITHUB_REPO'] = repo
        
        print("✅ GitHub configuration completed!")
    else:
        print("⏭️ Skipping GitHub configuration")

def setup_report_config(env_vars):
    """Setup report management configuration"""
    print_step(4, "Report Management (Optional)")
    
    max_reports = get_user_input("Max reports to keep", env_vars.get('MAX_REPORTS_TO_KEEP', '30'), required=False)
    env_vars['MAX_REPORTS_TO_KEEP'] = max_reports
    
    cleanup_days = get_user_input("Cleanup reports after (days)", env_vars.get('REPORTS_CLEANUP_DAYS', '30'), required=False)
    env_vars['REPORTS_CLEANUP_DAYS'] = cleanup_days
    
    auto_cleanup = get_user_input("Enable auto cleanup? (true/false)", env_vars.get('ENABLE_REPORT_CLEANUP', 'true'), required=False)
    env_vars['ENABLE_REPORT_CLEANUP'] = auto_cleanup
    
    notification_type = get_user_input("Notification type (new_posts/test)", env_vars.get('NOTIFICATION_TYPE', 'new_posts'), required=False)
    env_vars['NOTIFICATION_TYPE'] = notification_type
    
    print("✅ Report management configuration completed!")

def test_configuration():
    """Test the configuration"""
    print_step(5, "Configuration Testing")
    
    try:
        print("🔧 Testing configuration...")
        
        # Import and test
        from report_config import get_system_status
        status = get_system_status()
        
        print(f"   AI Configured: {'✅' if status['config_status']['ai_configured'] else '❌'}")
        print(f"   Email Configured: {'✅' if status['config_status']['email_configured'] else '❌'}")
        print(f"   GitHub Configured: {'✅' if status['config_status']['github_configured'] else '❌'}")
        print(f"   System Ready: {'✅' if status['system_ready'] else '❌'}")
        
        if status['config_status']['missing_config']:
            print("⚠️ Missing configuration:")
            for item in status['config_status']['missing_config']:
                print(f"   - {item}")
        
        if status['system_ready']:
            print("🎉 Configuration test passed!")
        else:
            print("⚠️ Some configuration is missing, but basic functionality should work")
        
        return status['system_ready']
        
    except Exception as e:
        print(f"❌ Configuration test failed: {e}")
        return False

def main():
    """Main setup function"""
    print_header("Microsoft Edge Competitive Intelligence - Configuration Setup")
    
    print("🚀 This helper will guide you through setting up your environment configuration.")
    print("💡 You can re-run this script anytime to update your configuration.")
    
    # Load existing configuration
    env_vars = load_existing_env()
    
    if env_vars:
        print(f"\n📄 Found existing .env file with {len(env_vars)} variables")
        update = get_user_input("Update existing configuration? (y/n)", "y", required=False).lower()
        if update not in ['y', 'yes']:
            print("👋 Setup cancelled")
            return
    
    try:
        # Setup configuration sections
        setup_ai_config(env_vars)
        setup_email_config(env_vars)
        setup_github_config(env_vars)
        setup_report_config(env_vars)
        
        # Save configuration
        print_step("FINAL", "Saving Configuration")
        save_env_file(env_vars)
        
        # Test configuration
        success = test_configuration()
        
        # Final instructions
        print_header("Setup Complete!")
        
        if success:
            print("🎉 Your configuration is ready!")
            print("\n📋 Next steps:")
            print("   1. Run the monitoring pipeline:")
            print("      uv run python production_pipeline.py")
            print("   2. Or run integration tests:")
            print("      uv run python test_phase2_integration.py")
        else:
            print("⚠️ Configuration has some missing items.")
            print("   Basic functionality should still work.")
            print("   Review the ENVIRONMENT_SETUP.md file for complete setup instructions.")
        
        print("\n📚 Additional resources:")
        print("   - ENVIRONMENT_SETUP.md: Detailed configuration guide")
        print("   - README.md: Usage instructions")
        print("   - production_pipeline.py --help: Command line options")
        
    except KeyboardInterrupt:
        print("\n\n⏹️ Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()